version: "3.8"
services:
  api:
    build:
      context: .
    env_file:
      - .env
    container_name: hiding_data_api
    restart: unless-stopped
    ports:
      - "127.0.0.1:3008:8000"
    networks:
      - hiding_data_network
      - postgres_network
      - rabbitmq_rabbit-net
      - loki_default

  worker:
    build:
      context: .
    command: faststream run broker_app:app --workers 1
    env_file:
      - .env
    container_name: hiding_data_worker
    restart: unless-stopped
    networks:
      - hiding_data_network
      - postgres_network
      - rabbitmq_rabbit-net
      - loki_default

networks:
  hiding_data_network:
    name: hiding_data_network
  rabbitmq_rabbit-net:
    external: true
  postgres_network:
    external: true
  loki_default:
    external: true
